# Generated by Django 6.0.2 on 2026-02-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0002_alter_contrato_cliente'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(help_text='Ex: https://suaempresa.atlassian.net')),
                ('cloud_id', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('api_token', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_connection', to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='JiraIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(max_length=60, unique=True)),
                ('key', models.CharField(max_length=30, unique=True)),
                ('project_key', models.CharField(blank=True, max_length=20, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=60, null=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=80, null=True)),
                ('priority', models.CharField(blank=True, max_length=80, null=True)),
                ('assignee_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('assignee_display_name', models.CharField(blank=True, max_length=160, null=True)),
                ('reporter_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('reporter_display_name', models.CharField(blank=True, max_length=160, null=True)),
                ('labels', models.JSONField(blank=True, null=True)),
                ('components', models.JSONField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('jira_created_at', models.DateTimeField(blank=True, null=True)),
                ('jira_updated_at', models.DateTimeField(blank=True, null=True)),
                ('jira_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_estimate_seconds', models.IntegerField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_issues', to='clientes.cliente')),
                ('contrato', models.ForeignKey(blank=True, help_text='Opcional: se você conseguir mapear issue -> contrato', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_issues', to='contratos.contrato')),
                ('tarefa_local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_issues', to='tarefas.tarefa')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'contrato', 'status'], name='jira_sync_j_cliente_84de53_idx'), models.Index(fields=['project_key', 'jira_updated_at'], name='jira_sync_j_project_24d70d_idx')],
            },
        ),
    ]
