# Generated by Django 6.0.2 on 2026-02-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(max_length=60)),
                ('key', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(blank=True, help_text='software, service_desk, business', max_length=50, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('lead_account_id', models.CharField(blank=True, max_length=120, null=True)),
                ('lead_display_name', models.CharField(blank=True, max_length=160, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jira_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jira_sync.jiraconnection')),
            ],
            options={
                'indexes': [models.Index(fields=['jira_connection', 'key'], name='jira_sync_j_jira_co_8af30c_idx'), models.Index(fields=['jira_connection', 'archived'], name='jira_sync_j_jira_co_142459_idx')],
                'unique_together': {('jira_connection', 'key')},
            },
        ),
    ]
