# Generated by Django 6.0.2 on 2026-02-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClienteMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LIDER', 'Líder'), ('GERENTE_PROJETO', 'Gerente de Projeto'), ('ANALISTA', 'Analista')], default='ANALISTA', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clientes.cliente')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'role', 'ativo'], name='accounts_us_cliente_bb7306_idx')],
                'unique_together': {('user', 'cliente')},
            },
        ),
    ]
