# Generated by Django 6.0.2 on 2026-02-13 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userclientemembership',
            index=models.Index(fields=['user', 'ativo'], name='accounts_us_user_id_b1c164_idx'),
        ),
    ]
