# Generated by Django 6.0.2 on 2026-02-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('zabbix_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostid', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'hostid')},
            },
        ),
        migrations.CreateModel(
            name='ZabbixProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=255)),
                ('severidade', models.IntegerField()),
                ('inicio', models.DateTimeField()),
                ('reconhecido', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zabbix_integration.zabbixhost')),
            ],
            options={
                'unique_together': {('cliente', 'eventid')},
            },
        ),
        migrations.CreateModel(
            name='ZabbixTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggerid', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('prioridade', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('ultima_alteracao', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'triggerid')},
            },
        ),
    ]
