# Generated by Django 6.0.2 on 2026-02-10 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('zabbix_integration', '0002_zabbixhost_zabbixproblem_zabbixtrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value_type', models.IntegerField()),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('delay', models.CharField(blank=True, max_length=50, null=True)),
                ('lastvalue', models.TextField(blank=True, null=True)),
                ('lastclock', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zabbix_integration.zabbixhost')),
            ],
        ),
        migrations.CreateModel(
            name='ZabbixHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.DateTimeField()),
                ('value', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='zabbix_integration.zabbixitem')),
            ],
        ),
        migrations.CreateModel(
            name='ZabbixEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('clock', models.DateTimeField()),
                ('raw', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zabbix_integration.zabbixhost')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'clock'], name='zabbix_inte_cliente_a791cc_idx'), models.Index(fields=['cliente', 'severity'], name='zabbix_inte_cliente_9946c1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='zabbixitem',
            index=models.Index(fields=['cliente', 'host', 'key'], name='zabbix_inte_cliente_785595_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zabbixitem',
            unique_together={('cliente', 'itemid')},
        ),
        migrations.AddIndex(
            model_name='zabbixhistory',
            index=models.Index(fields=['cliente', 'item', 'clock'], name='zabbix_inte_cliente_cee0da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zabbixhistory',
            unique_together={('item', 'clock')},
        ),
    ]
