# Generated by Django 6.0.2 on 2026-02-11 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('zabbix_integration', '0003_zabbixitem_zabbixhistory_zabbixevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('slo', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'name'], name='zabbix_inte_cliente_5c1041_idx')],
                'unique_together': {('cliente', 'slaid')},
            },
        ),
        migrations.CreateModel(
            name='ZabbixTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'name'], name='zabbix_inte_cliente_2053cd_idx')],
                'unique_together': {('cliente', 'templateid')},
            },
        ),
        migrations.CreateModel(
            name='ZabbixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('surname', models.CharField(blank=True, max_length=120, null=True)),
                ('roleid', models.CharField(blank=True, max_length=50, null=True)),
                ('user_groups', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'username'], name='zabbix_inte_cliente_df02f3_idx')],
                'unique_together': {('cliente', 'userid')},
            },
        ),
    ]
