# Generated by Django 6.0.2 on 2026-02-11 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('zabbix_integration', '0004_zabbixsla_zabbixtemplate_zabbixuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('severity', models.IntegerField(default=0)),
                ('acknowledged', models.BooleanField(default=False)),
                ('clock', models.DateTimeField()),
                ('hostid', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'severity'], name='zabbix_inte_cliente_d01b08_idx'), models.Index(fields=['cliente', 'clock'], name='zabbix_inte_cliente_d47d05_idx')],
                'unique_together': {('cliente', 'eventid')},
            },
        ),
        migrations.CreateModel(
            name='ZabbixAlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('clock', models.DateTimeField()),
                ('hostid', models.CharField(blank=True, max_length=50, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'clock'], name='zabbix_inte_cliente_7b627a_idx'), models.Index(fields=['cliente', 'severity'], name='zabbix_inte_cliente_5c38b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ZabbixAlertSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertid', models.CharField(max_length=50, unique=True)),
                ('eventid', models.CharField(blank=True, max_length=50, null=True)),
                ('clock', models.DateTimeField()),
                ('sendto', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'clock'], name='zabbix_inte_cliente_b2a790_idx')],
            },
        ),
    ]
