# Generated by Django 6.0.2 on 2026-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0005_zabbixalarm_zabbixalarmevent_zabbixalertsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='hostname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
