# Generated by Django 6.0.2 on 2026-02-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0006_zabbixevent_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='hostid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
