# Generated by Django 6.0.2 on 2026-02-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0007_zabbixevent_hostid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhost',
            name='objectid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
