# Generated by Django 6.0.2 on 2026-02-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0008_zabbixhost_objectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='objectid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zabbixevent',
            name='objectname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
