# Generated by Django 6.0.2 on 2026-02-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0009_zabbixevent_objectid_zabbixevent_objectname'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zabbix_integration.zabbixtrigger'),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='hosts',
            field=models.ManyToManyField(blank=True, related_name='triggers', to='zabbix_integration.zabbixhost'),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
