# Generated by Django 6.0.2 on 2026-02-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0010_zabbixevent_trigger_zabbixtrigger_hosts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zabbixitem',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='zabbix_integration.zabbixhost'),
        ),
    ]
