# Generated by Django 6.0.2 on 2026-02-23 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0011_alter_zabbixitem_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='hosts',
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='zabbix_integration.zabbixitem'),
        ),
    ]
