# Generated by Django 6.0.2 on 2026-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0012_remove_zabbixtrigger_hosts_zabbixtrigger_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhost',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
