# Generated by Django 6.0.2 on 2026-02-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametro', '0003_alter_itensmonitoramento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrocliente',
            name='valor',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
