# Generated by Django 6.0.2 on 2026-02-13 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATO_PRINCIPAL', 'Contrato principal'), ('ADITIVO', 'Aditivo'), ('ANEXO', 'Anexo'), ('OUTRO', 'Outro')], default='CONTRATO_PRINCIPAL', max_length=30)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('arquivo', models.FileField(upload_to='contratos/pdfs/')),
                ('nome_original', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('tamanho_bytes', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('extraido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='contratos.contrato')),
                ('extraido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_arquivos_extraidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContratoClausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('extraida_por_ia', models.BooleanField(default=False)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='contratos.contrato')),
                ('fonte_arquivo', models.ForeignKey(blank=True, help_text='Arquivo (PDF) usado como fonte desta cláusula', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clausulas', to='contratos.contratoarquivo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='contratoarquivo',
            index=models.Index(fields=['contrato', 'tipo', 'versao'], name='contratos_c_contrat_780266_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoarquivo',
            index=models.Index(fields=['contrato', 'criado_em'], name='contratos_c_contrat_1ffcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoclausula',
            index=models.Index(fields=['contrato', 'ordem'], name='contratos_c_contrat_3dffdc_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoclausula',
            index=models.Index(fields=['contrato', 'numero'], name='contratos_c_contrat_536023_idx'),
        ),
        migrations.AddIndex(
            model_name='contratoclausula',
            index=models.Index(fields=['fonte_arquivo'], name='contratos_c_fonte_a_44891b_idx'),
        ),
    ]
