# Generated by Django 6.0.2 on 2026-02-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_contratoarquivo_contratoclausula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('responsavel_sugerido', models.CharField(blank=True, max_length=80, null=True)),
                ('prioridade', models.CharField(blank=True, max_length=20, null=True)),
                ('prazo_dias_sugerido', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20)),
                ('gerada_por_ia', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clausula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='contratos.contratoclausula')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_contrato', to='contratos.contrato')),
            ],
            options={
                'indexes': [models.Index(fields=['contrato', 'status'], name='contratos_c_contrat_41ecf6_idx'), models.Index(fields=['clausula'], name='contratos_c_clausul_2c3b8a_idx')],
            },
        ),
    ]
