# Generated by Django 6.0.2 on 2026-02-18 12:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0004_contratotarefa'),
        ('tarefas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RODANDO', 'Rodando'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='RODANDO', max_length=20)),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('segundos_trabalhados', models.PositiveIntegerField(default=0)),
                ('segundos_pausados', models.PositiveIntegerField(default=0)),
                ('ultimo_inicio_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_pause_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='tarefas.tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefa_timers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TarefaTimerPausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pausas', to='contratos.tarefatimer')),
            ],
        ),
        migrations.AddIndex(
            model_name='tarefatimer',
            index=models.Index(fields=['tarefa', 'usuario', 'estado'], name='contratos_t_tarefa__e01ea2_idx'),
        ),
    ]
