# Generated by Django 6.0.2 on 2026-02-18 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0005_tarefatimer_tarefatimerpausa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefatimer',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='contratos.contratotarefa'),
        ),
    ]
