# Generated by Django 6.0.2 on 2026-02-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0009_copilotactionlog_copilotrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proposta_tecnica_md',
            field=models.TextField(blank=True, null=True),
        ),
    ]
