# Generated by Django 6.0.2 on 2026-02-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0010_contrato_proposta_tecnica_md'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarquivo',
            name='tipo',
            field=models.CharField(choices=[('CONTRATO_PRINCIPAL', 'Contrato principal'), ('ADITIVO', 'Aditivo'), ('ANEXO', 'Anexo'), ('PROPOSTA_TECNICA', 'Proposta técnica'), ('OUTRO', 'Outro')], default='CONTRATO_PRINCIPAL', max_length=30),
        ),
    ]
